from setuptools import setup, find_packages

setup(
    name="federatedscope",
    version="0.3.0",
    description="Eloquence Federated LLM based on FederatedScope repository",
    long_description_content_type="text/markdown",
    author="Jordi Luque, Aleix Sant",
    author_email="jordi.luque@telefonica.com, aleix.santsavall@telefonica.com",
    python_requires="==3.9.*",
    packages=find_packages(),
    install_requires=[
        'numpy<1.23.0',
        'scikit-learn==1.0.2',
        'scipy==1.7.3',
        'pandas',
        'grpcio>=1.45.0',
        'grpcio-tools',
        'pyyaml>=5.1',
        'fvcore',
        'iopath',
        'wandb',
        'tensorboard',
        'tensorboardX',
        'pympler',
        'protobuf==3.19.4',
        'matplotlib',
        'dill',
        'torch==2.4.1',
        'torchaudio==2.4.1', 
        'torchvision==0.19.1',
        'deepspeed',
        'cupy-cuda12x',
        'tokenizers==0.21.0',
        'transformers==4.48.2',
        'accelerate==0.20.3',
        'peft==0.3.0',
        'sentencepiece==0.1.99',
    ],
)