criterion:
  type: CrossEntropyLoss
data:
  root: data/
  splits:
  - 0.98
  - 0.01
  - 0.01
  splitter: iid
  type: alpaca_cleaned_en.jsonl@llm
  domain_type: cross
dataloader:
  batch_size: 1
device: 2
early_stop:
  patience: 1
eval:
  count_flops: false
  freq: 5
  split:
  - val
  metrics:
  - loss
  len_server_dataset: 1000
  best_res_update_round_wise_key: val_avg_loss
expname_tag: ds_1c_5000r_r8_a16_1pat_160lts_fedavg
federate:
  client_num: 2
  master_port: 26100
  method: FedAvg
  mode: distributed
  online_aggr: false
  process_num: 1
  adapt_save_to: finetuned_adapters/distributed/alpaca_cleaned_en/phi-1_5/federated/standard/ds_1c_5000r_r8_a16_1pat_160lts_fedavg.ckpt
  share_local_model: false
  total_round_num: 5000
  use_global_early_stop: True
  use_LDES: False
  shuffle_all_data: False
  shuffle_train_clients: False
  shuffle_val_clients: False
  shuffle_test_clients: False
  shuffle_per_client: True
  make_global_eval: True
  make_clients_eval: True
  ignore_weight: True
distribute:
  use: True
  server_host: '192.168.24.120'
  server_port: 11009
  client_host: '192.168.24.117'
  client_port: 50062
  role: 'client'
  data_idx: 1
  grpc_max_send_message_length: 1048576000
  grpc_max_receive_message_length: 1048576000
llm:
  adapter:
    args:
    - adapter_method: lora
      adapter_package: peft
      lora_alpha: 16
      lora_dropout: 0.05
      r: 8
      target_modules:
      - q_proj
      - k_proj
      - v_proj
      - o_proj
    use: true
  chat:
    max_len: 1500
  deepspeed:
    ds_config: federatedscope/llm/deepspeed/ds_config_32bs_16grad_1mbs.json
    use: true
  tok_len: 1300
  prompt_path: prompt_templates/alpaca_cleaned_8c
  model_save_to: models_with_ft_adapt/distributed/alpaca_cleaned_en/early_stop/phi-1_5/fedavg
model:
  type: microsoft/phi-1_5@huggingface_llm
train:
  batch_or_epoch: batch
  is_enable_half: true
  local_update_steps: 160
  optimizer:
    lr: 0.001
    weight_decay: 0.0
trainer:
  type: llmtrainer
grad:
  grad_clip: 1.0
use_gpu: true
